services:
  db:
    image: postgres:16
    container_name: db_app
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5435:5432"
    env_file:
      - .env-none-dev

  app:
    build:
      context: .
    env_file:
      - .env-none-dev
    container_name: fastapi_app
    command:
      ["/fastapi_app/docker/app.sh"]
    ports:
      - "9999:8000"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge