"""add imageUrl on product to String

Revision ID: 5dcb6b5d1355
Revises: 
Create Date: 2024-05-22 20:56:44.596915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dcb6b5d1355'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'imageUrl',
               existing_type=sa.NUMERIC(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'imageUrl',
               existing_type=sa.String(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    # ### end Alembic commands ###
