"""delete des, weight in product

Revision ID: a8a8a0dcd30d
Revises: c38a86fd2167
Create Date: 2024-06-11 13:08:30.285446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8a8a0dcd30d'
down_revision: Union[str, None] = 'c38a86fd2167'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'total_price',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(),
               existing_nullable=True)
    op.drop_column('product', 'weight')
    op.drop_column('product', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('product', sa.Column('weight', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.alter_column('orders', 'total_price',
               existing_type=sa.Numeric(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
