"""add models for order fix

Revision ID: c38a86fd2167
Revises: f32b8a8a6df2
Create Date: 2024-06-09 17:45:22.781485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c38a86fd2167'
down_revision: Union[str, None] = 'f32b8a8a6df2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('total_price', sa.Integer(), nullable=True))
    op.drop_constraint('orders_user_id_key', 'orders', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('orders_user_id_key', 'orders', ['user_id'])
    op.drop_column('orders', 'total_price')
    # ### end Alembic commands ###
