"""add models for order fix

Revision ID: f32b8a8a6df2
Revises: a281b05cbb28
Create Date: 2024-06-09 16:02:04.365394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f32b8a8a6df2'
down_revision: Union[str, None] = 'a281b05cbb28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_items_order_item_id_key', 'order_items', type_='unique')
    op.create_unique_constraint(None, 'order_items', ['id'])
    op.drop_column('order_items', 'order_item_id')
    op.create_unique_constraint(None, 'orders', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='unique')
    op.add_column('order_items', sa.Column('order_item_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'order_items', type_='unique')
    op.create_unique_constraint('order_items_order_item_id_key', 'order_items', ['order_item_id'])
    # ### end Alembic commands ###
